spring:
   mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: edpas.demo@gmail.com
    password: edpas-2019
    port: 587
    properties:
      mail:
        ssl:
          enable: true
        smtp:
          auth: true
          starttls:
            enable: true       
            required: true     
    protocol: smtp
    test-connection: false